config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  post 'favorite_language', to: 'users#favorite_language'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index;end

  def favorite_language
    username = params[:username]

    if username.blank?
      flash[:alert] = 'Please provide a GitHub username.'
    else
      begin
        favorite_language = GithubService.get_favorite_language(username)
        flash[:notice] = "The favorite programming language of #{username} is #{favorite_language}."
      rescue StandardError => e
        flash[:alert] = e.message
      end
    end

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubFavoriteLanguage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Github Favorite Language</title>
</head>
<body>
<h1>Github Favorite Language</h1>

<% flash.each do |key, message| %>
  <div class="<%= key %>">
    <%= message %>
  </div>
<% end %>

<%= form_tag favorite_language_path, method: :post do %>
  <%= text_field_tag :username %>
  <%= submit_tag 'Submit' %>
<% end %>
</body>
</html>